/*used for label description of the variables in the Merged data file*/
*Erica Bianca Guillermo
use "C:\Users\jynion\Google Drive\jy_mrt_files\MRT - IGA\IGA - BD\IGA BD stat analysis\MergedDataBD.dta"

label variable hhid "Unique Household ID"
label variable resid "Respondent ID"
label variable session "session"
label variable hh "Household ID per session"
label variable district "District"
label variable village "Village"
label variable date "Date"
label variable morning "Morning Session"
label variable market "Market Information"
label variable climate "Climate Information"
label variable slvti "VTI for Slenderness"
label variable unvti "VTI for Unstickiness"
label variable arvti "VTI for Aroma"
label variable hrvti "VTI for Head Rice Recovery"
label variable ltvti "VTI for Lodging Tolerance"
label variable drvti "VTI for Disease Resistance"
label variable irvti "VTI for Insect Resistance"
label variable atvti "VTI for Abiotic Stress Tolerance"
label variable rsvti "VTI for Reduction to Shattering"
label variable eavti "VTI for Earliness"
label variable sdvti "VTI for Straw Digestibility"
label variable sldis "distances for Slenderness"
label variable undis "distances for Unstickiness"
label variable ardis "distances for Aroma"
label variable hrdis "distances for Head Rice Recovery"
label variable ltdis "distances for Lodging Tolerance"
label variable drdis "distances for Disease Resistance"
label variable irdis "distances for Insect Resistance"
label variable atdis "distances for Abiotic Stress Tolerance"
label variable rsdis "distances for Reduction to Shattering"
label variable eadis "distances for Earliness"
label variable sddis "distances for Straw Digestibility"
label variable slrk "risk for Slenderness"
label variable unrk "risk for Unstickiness"
label variable arrk "risk for Aroma"
label variable hrrk "risk for Head Rice Recovery"
label variable ltrk "risk for Lodging Tolerance"
label variable drrk "risk for Disease Resistance"
label variable irrk "risk for Insect Resistance"
label variable atrk "risk for Abiotic Stress Tolerance"
label variable rsrk "risk for Reduction to Shattering"
label variable eark "risk for Earliness"
label variable sdrk "risk for Straw Digestibility"
label variable slinv "Investment shares for Slenderness"
label variable uninv "Investment shares for Unstickiness"
label variable arinv "Investment shares for Aroma"
label variable hrinv "Investment shares for Head Rice Recovery"
label variable ltinv "Investment shares for Lodging Tolerance"
label variable drinv "Investment shares for Disease Resistance"
label variable irinv "Investment shares for Insect Resistance"
label variable atinv "Investment shares for Abiotic Stress Tolerance"
label variable rsinv "Investment shares for Reduction to Shattering"
label variable eainv "Investment shares for Earliness"
label variable sdinv "Investment shares for Straw Digestibility"
label variable uinv "Uninvested"
label variable tot "Total Invesment+ uninvested"
label variable traitsno "Number of traits invested"
label variable totinv "Percent invested"
label variable dret "Deterministic return"
label variable dominance "Dominance in joint round"
label variable disp "Disposal of model variety"
label variable eucd "Euclidean Distance"
label variable ihdmp1 "Intra-household decision-making making power1"
label variable ihdmp2 "Intra-household decision-making making power (percentage)"
label variable dom1 "Whether husband is dominant during joint round"
label variable dom2 "Whether wife is dominant during joint round"
label variable cons "Whether the model variety is consumed only"
label variable sell "Whether the model variety is sold only"
label variable gqlty "Grain quality investment share (SL,UN,AR,HR)"
label variable gloss "Loss reduction investment share (IR,DR,LT,AT,RS)"
label variable eainv2 "Earliness Investment shares (for cluster traits)"
label variable sdinv2 "Straw Digestibility Investment shares (for cluster traits)"
label variable uinv2 "uninvested for cluster trait"
label variable tot2 "total invested for cluster trait"
label variable resp "Respondent"
label variable season "Season"
label variable season2 "Season2"
label variable resph "Respondent for husband"
label variable respw "Respondent for wife"
label variable age "Age"
label variable ageh "Age of husband"
label variable agew "Age of wife"
label variable educ "Years of schooling"
label variable educh "Years of schooling of husband"
label variable educw "Years of schooling of husband"
label variable exp "Years of farming experience"
label variable exph "Years of farming experience of husband"
label variable expw "Years of farming experience of wife"
label variable occ1 "Primary occupation (at least one farming/agriculture wage labor)"
label variable occ1h "Primary occupation (husband in farming/agriculture wage labor)"
label variable occ1w "Primary occupation (wife in farming/agriculture wage labor)"
label variable rel1 "Religion "
label variable smph1 "Owning a smartphone (at least one  for joint)"
label variable org1 "Member of any organization (at least one is for joint)"
label variable train1 "Attended a training (at least one for joint)"
label variable train1h "Attended a training (husband)"
label variable train1w "Attended a training (wife)"
label variable riskpref11 "Time preference (discounting rate)"
label variable riskpref11h "Time preference of husband discounting rate)"
label variable riskpref11w "Time preference of wife(discounting rate)"
label variable riskpref21 "investment preference in farming (max for joint)"
label variable riskpref21h "investment preference in farming of husband"
label variable riskpref21w "investment preference in farming of wife"
label variable choice11 "factors that influence decision making in IGA () (at least one for joint)"
label variable choice21 "factors that influence decision making in IGA (at least one for joint)"
label variable revqand1 "Review question (at least one have perfect score/have the two correct answer)"
label variable revqor1 "Review question (at least one have at least one quiz questions that is correct)"
label variable occ2 "Primary occupation (both have farming/agriculture wage labor for joint)"
label variable train2 "Attended a training (both farmers for joint)"
label variable org2 "Member of any organization (both farmers for joint)"
label variable choice12 "factors that influence decision making in IGA  (both farmers for joint)"
label variable choice22 "factors that influence decision making in IGA  (both farmers for joint)"
label variable rel2 "Religion2 "
label variable smph2 "both owns a smartphone"
label variable revqand2 "Review question21"
label variable revqor2 "Review question22"


label variable parea "Proportion of rice area planted for all variety"
label variable seedrate "amount of seed used per ha"
label variable prsold "proportion of sold in paddy"
label variable price "price received in selling of paddy "
label variable districe "distance to market for rice paddy (in km)"
label variable pssold "Proportion of sold in straw"
label variable pstraw "price received in selling straw"
label variable diststraw "distance to market for straw (in km)"


label variable hhsize "Household size"
label variable repinc "Reported annual income"
label variable repinc2 "Reported annual income (in '000) "
label variable income "Annual income"
label variable yfarmers1 "whether household has a member aged 15-24y/o active in rice farming"
label variable ownha "Own cultivated area (in ha)"
label variable leaseha "leased/share area (in ha)"
label variable totland "total land area (in ha)"
label variable perlease "Percentage of leased area"
label variable ab "Did you experience any constraints from abiotic stress in rice production and marketing in the last 2 years?"
label variable dis "Did you experience any constraints from disease in rice production and marketing in the last 2 years?"
label variable ins "Did you experience any constraints from insect in rice production and marketing in the last 2 years?"
label variable lod "Did you experience any constraints from lodging in rice production and marketing in the last 2 years?"
label variable sh "Did you experience any constraints from shattering of grains in rice production and marketing in the last 2 years?"
label variable late "Did you experience any constraints from late maturing in rice production and marketing in the last 2 years?"
label variable headrice "Did you experience any constraints from lower price from buyers due to lower head rice recovery in rice production and marketing in the last 2 years?"
label variable absev "Maximum severity of constraint from abiotic stresses"
label variable dissev "Maximum severity of constraint from disease"
label variable inssev "Maximum severity of constraint from insect"
label variable lodsev "Severity of constraint from lodging"
label variable shsev "Severity of constraint from shattering"
label variable latesev "Severity of constraint from late maturing"
label variable headricesev "Severity of constraint from lower price from buyers due to lower head rice recovery"
label variable std "Do buyers require certain quality standards of your paddy?"
label variable knowendmkt "knowledge of end market for their rice crop"
label variable straw "Do you sell straw?"
label variable extinfo "Are you connected with extension personnel/department?"
label variable borrow "Do you borrow?"
label variable crop_grow "What crop to grow"
label variable ricevar_grow "What rice variety to grow"
label variable amt_ricedisp "Amount of rice to store or sell"
label variable where_sell "Where to sell the rice crop"
label variable when_sell "When to sell the rice crop"
label variable nextseason_crop "What crop type and seeds to grow in the next season"
label variable cropsell_spend "Who decides how to spend income from crop sale"
label variable where_storess~s "Where to store seeds"
label variable mdvarswarna "Model variety is Swarna"
label variable mdvarbr49 "Model variety is BRRI dhan49"
label variable bothconssell "both consumed and sold"
label variable hybrid "Model variety is hybrid"
label variable aroma "Model variety is aromatic"
label variable yrelease "year of release of the model variety"
label variable maturity "Maturity of the model variety (DAS)"
label variable mdvarbr28 "Model variety is BRRI dhan28"
label variable mdvarbr50 "Model variety is BRRI dhan50"

label variable plntd_b28 "planted BRRI dhan28"
label variable source_seed_b28 "source of seed for BRRI dhan28"
label variable buyer1_b28 "buyer for BRRI dhan28"
label variable price1_b28 "price of BRRI dhan28 (imputed)"
label variable distance1_b28 "distance to market - BRRI dhan28"
label variable price_rice_b28 "price of BRRI dhan28"
label variable plntd_b49 "planted BRRI dhan49"
label variable source_seed_b49 "source of seed for BRRI dhan49"
label variable buyer1_b49 "buyer for BRRI dhan49"
label variable price1_b49 "price of BRRI dhan49 (imputed)"
label variable distance1_b49 "distance to market - BRRI dhan49"
label variable price_rice_b49 "price of BRRI dhan49"
label variable plntd_b50 "planted BRRI dhan50"
label variable source_seed_b50 "source of seed for BRRI dhan50"
label variable buyer1_b50 "buyer for BRRI dhan50"
label variable price1_b50 "price of BRRI dhan50 (imputed)"
label variable distance1_b50 "distance to market - BRRI dhan50"
label variable price_rice_b50 "price of BRRI dhan50"
label variable plntd_guti "planted Gutiswarna"
label variable source_seed_g~i "source of seed for Gutiswarna"
label variable buyer1_guti "buyer1 for Gutiswarna"
label variable price1_guti "price1 of Gutiswarna (imputed)"
label variable distance1_guti "distance1 to market - Gutiswarna"
label variable buyer2_guti "buyer2 for Gutiswarna"
label variable price2_guti "price2 of Gutiswarna  (imputed)"
label variable distance2_guti "distance2 to market - Gutiswarna"
label variable price_rice_guti "price of Gutiswarna"

label variable variety "model variety+variety with largest plot area"
label variable year "year planted"
label variable conv_area "plot size of replacement var+var with largest plot area (ha)"
label variable conv_prod "production of replacement var"
label variable yield "yield of replacement var"
label variable conv_sold "yield sold of replacement var"
label variable per_sold "prop of sold of replacement var"
label variable buyer1 "buyer of replacement var"
label variable reason1 "reason for selling to buyer"
label variable price1 "output price"
label variable distance1 "distance top market of replacement var"
label variable price_rice "price of replacement var (imputed)"
label variable match "replacement variety is matched with var planted"
label variable varietymax "variety with largest plot area"
label variable pareamax "Proportion of rice area planted for replacement variety"

label variable ab_minor "experience minor abiotic constraint in rice"
label variable ab_mod "experience moderate abiotic constraint in rice"
label variable ab_serious "experience serious abiotic constraint in rice"
label variable dis_minor "experience minor disease constraint in rice"
label variable dis_mod "experience moderate disease constraint in rice"
label variable dis_serious "experience serious disease constraint in rice"
label variable ins_minor "experience minor insect constraint in rice"
label variable ins_mod "experience moderate insect constraint in rice"
label variable ins_serious "experience serious insect constraint in rice"

label variable	riskneutral	"neutral to risk investment in farming"
label variable	risklikely	"likely to risk investment in farming"
label variable	riskexlikely	"extremely likely to risk investment in farming"
label variable	riskunlikely	"unlikely to risk investment in farming"

/*-----------------------defining the value labels for variables ----------------------*/
label define   severity 1 "Not at all a problem" 2 "Minor problem" 3 "Moderate problem" 4  "Serious problem"    
label define  experience2 1  "if both husband and wife answered Past and current experience" 0 "otherwise"        
label define  qscore100 1 "if both husband and wife are correct for both answer" 0 "otherwise"        
label define  qscore50 1 "if both husband and wife are correct in one question" 0 "otherwise"        
label define  standards 1 "buyers require certain quality standards" 0 "otherwise"        
label define  disposal 1 "consumption only" 2 "selling only" 3 "both cons and sell"      
label define  q2score100 1 "correct for both answer" 0 "otherwise"        
label define  q2score50 1 "correct for one question" 0 "otherwise"        
label define  rating 1 "Extremely unlikely" 2 "Unlikely" 3  "Neutral" 4  "Likely" 5 "Extremely likely"  
label define  decision 1 "H only (Husband only)" 2 "H>W (Husband dominates)" 3  "H=W (Both husband and wife)" 4  "W>H (Wife dominates)" 5 "W only (Wife only)" 9 "N/A (Husband and wife not involved)"
label define  domin 1 "husband" 2 "wife" 3  "both"      
label define  oexperience2 1 "if both husband and wife answered own experience/ problems faced" 0 "otherwise"        
label define  districts 1 "Jessore" 0 "Rangpur"        
label define  model 1 "model variety of farmer is the same with the joint round" 0 "model variety of farmer is different with the joint round"        
label define  sess 1 "morning" 0  "afternoon"        
label define  relig 1 "Muslim" 0 "otherwise"        
label define  oexperience1 1 "Own farm experience/ problems faced" 0 "otherwise"        
label define  experience1 1 "Past and current experience" 0 "otherwise"        
label define  wetdry 1 "wet" 0 "dry"        
label define  yesno 1 "yes" 0 "no"        
label define  yrrel 1 "released Before 1990" 0 "otherwise (after 1990 released variety)"       
label define  daymat 1 "Late (Above 140 days)" 0 "Early to medium ( 100 to 140 days)"   

          

label dir /*to define the directory*/
label list /*to see the list of vlaue labels in the directory*/

/* defining value labels for each variable*/
label value absev dissev inssev lodsev shsev latesev headricesev severity
label value choice22 experience2 
label value revqand2 qscore100
label value revqor2 qscore50   
label value std standards
label value disp disposal 
label value revqand1 q2score100
label value revqor1 q2score50 
label value riskpref21 rating 
label value crop_grow ricevar_grow amt_ricedisp where_sell when_sell nextseason_crop cropsell_spend where_storess~s  decision 
label value dominance domin 
label value choice12 oexperience2 
label value district districts 
label value ihdmp1 model 
label value morning sess 
label value rel1 relig 
label value choice11 oexperience1 
label value choice21 experience1 
label value season2 wetdry
label value market climate dom1 dom2 cons sell resph respw ///
			occ1 smph1 org1 train1 occ2  train2 org2 yfarmers1 ab  dis /// 
			ins lod sh late headrice knowendmkt straw extinfo borrow ///
			mdvarswarna mdvarbr49 bothconssell hybrid aroma mdvarbr28 mdvarbr50 yesno
			
label value yrelease yrrel
label value maturity daymat 
label value	ab_minor ab_mod ab_serious dis_minor dis_mod dis_serious ins_minor ///
			ins_mod ins_serious riskneutral risklikely riskexlikely riskunlikely yesno


